### ISSUE TITLE
Can't  generate motions from texts (using test set)

### ISSUE THREAD

**Issue by YupeiLin2388** [EricGuo5513/TM2T#1]
When i run the  command 
`python evaluate_t2m_seq2seq.py --name T2M_Seq2Seq_NML1_Ear_SME0_N --num_results 10 --repeat_times 3 --sample --ext sample` 
The output is 
```
Traceback (most recent call last):
  File "evaluate_t2m_seq2seq.py", line 122, in <module>
    dataset = Motion2TextEvalDataset(opt, mean, std, split_file, w_vectorizer)
  File "/home/student/TM2T/data/dataset.py", line 538, in __init__
    with cs.open(pjoin(opt.m_token_dir, name + '.txt'), 'r') as f:
  File "/home/student/.conda/env/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './dataset/HumanML3D/VQVAEV3_CB1024_CMT_H1024_NRES3/004822.txt' 
```
I have downloaded the required dataset, but there is no **VQVAEV3_CB1024_CMT_H1024_NRES3**  file folder in the dataset folder. I have the same problem when I run the commands in **Translating motions into langauge (using test set)** .What should I do to get the **VQVAEV3_CB1024_CMT_H1024_NRES3**   file folder？

**Comment by YupeiLin2388** [comment]
I solved the problem by running `python tokenize_script.py --gpu_id 0 --name VQVAEV3_CB1024_CMT_H1024_NRES3 --dataset_name t2m `
