### ISSUE TITLE
No such file or directory: './dataset/HumanML3D/VQVAEV3_CB1024_CMT_H1024_NRES3\\004822.txt'

### ISSUE THREAD

**Issue by SeuGuoTong** [EricGuo5513/TM2T#13]
I will appreciate it if you could help me.
Traceback (most recent call last):
  File "evaluate_m2t_transformer.py", line 131, in <module>
    dataset = Motion2TextEvalDataset(opt, mean, std, split_file, w_vectorizer)
  File "D:\Graduate\my_direction\Text2gesture\code\TM2T-main\data\dataset.py", line 538, in __init__
    with cs.open(pjoin(opt.m_token_dir, name + '.txt'), 'r') as f:
  File "D:\ProgramData\anaconda3\envs\tm2t\lib\codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './dataset/HumanML3D/VQVAEV3_CB1024_CMT_H1024_NRES3\\004822.txt'

**Comment by SeuGuoTong** [comment]
i am running "python evaluate_m2t_transformer.py --name M2T_EL4_DL4_NH8_PS --gpu_id 0 --num_results 20 --n_enc_layers 4 --n_dec_layers 4 --proj_share_weight --ext beam_search"

**Comment by OWSJodie** [comment]
Hi @SeuGuoTong , have you managed to solve this problem as i also encounter this after importing the HumanML3D dataset.

**Comment by LvXinTao** [comment]
I think you may refer to #5 for solutions!

**Comment by OWSJodie** [comment]
> I think you may refer to #5 for solutions!

Tyvm, i manage to get pass the error using that solution.
