### ISSUE TITLE
could not find the `004822.npy` file

### ISSUE THREAD

**Issue by gitforziio** [EricGuo5513/TM2T#7]
I have downloaded the `HumanML3D` dataset to correct dir, but could not find the `004822.npy` file while `012314.npy` exists.

```
Loading t2m_model model: Epoch 031 Total_Iter 11904
  0%|                                                                                                                                    | 0/4384 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "evaluate_t2m_seq2seq.py", line 121, in <module>
    dataset = Motion2TextEvalDataset(opt, mean, std, split_file, w_vectorizer)
  File "C:\GITHERE\TM2T\data\dataset.py", line 532, in __init__
    motion = np.load(pjoin(opt.motion_dir, name + '.npy'))
  File "C:\Users\Bush\anaconda3\envs\TM2T\lib\site-packages\numpy\lib\npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/HumanML3D/new_joint_vecs\\004822.npy'
```

**Comment by EricGuo5513** [comment]
Hi, for HumanML3D, you need to run the code to obtain the datasets. https://github.com/EricGuo5513/HumanML3D

**Comment by gitforziio** [comment]
> Hi, for HumanML3D, you need to run the code to obtain the datasets. https://github.com/EricGuo5513/HumanML3D
Thank you! But I got some other error by running the code. Please turn to: https://github.com/EricGuo5513/HumanML3D/issues/11
